import axios from "axios";
import config from "../config";
import { WorldIDProof, WorldIDVerifyResult } from "../types";
import { createLogger } from "../utils/logging";

const log = createLogger("service:worldid");

/**
 * Verify a World ID zero-knowledge proof against the Worldcoin API.
 *
 * @param proof - The proof payload generated by IDKit on the client side.
 * @returns Verification result with nullifier hash and status.
 * @throws On network errors or if the proof is invalid.
 */
export async function verifyWorldIDProof(
  proof: WorldIDProof,
): Promise<WorldIDVerifyResult> {
  log.info("Verifying World ID proof", {
    nullifierHash: proof.nullifier_hash.slice(0, 12) + "…",
  });

  const payload = {
    merkle_root: proof.merkle_root,
    nullifier_hash: proof.nullifier_hash,
    proof: proof.proof,
    action: config.worldId.action,
    signal: proof.signal ?? "",
  };

  try {
    const response = await axios.post(
      `${config.worldId.apiUrl}/${config.worldId.appId}`,
      payload,
      {
        headers: { "Content-Type": "application/json" },
        timeout: 15_000,
      },
    );

    const isVerified: boolean = response.status === 200;

    const result: WorldIDVerifyResult = {
      verified: isVerified,
      nullifierHash: proof.nullifier_hash,
      action: config.worldId.action,
      verifiedAt: new Date().toISOString(),
    };

    log.info("World ID verification result", {
      verified: result.verified,
      nullifierHash: result.nullifierHash.slice(0, 12) + "…",
    });

    return result;
  } catch (err: any) {
    // World ID API returns 400 for invalid proofs
    if (err?.response?.status === 400) {
      log.warn("World ID proof rejected", {
        detail: err.response?.data?.detail ?? "invalid proof",
      });

      return {
        verified: false,
        nullifierHash: proof.nullifier_hash,
        action: config.worldId.action,
        verifiedAt: new Date().toISOString(),
      };
    }

    log.error("World ID verification error", { error: err.message });
    throw new Error(`World ID verification failed: ${err.message}`);
  }
}
